name: Build with Node.js

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup pnpm
      uses: pnpm/action-setup@v2.4.0
      with:
        version: 8.8.*
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install
    - name: Build
      run: pnpm build
      
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Configure GitHub Pages
      uses: actions/configure-pages@v3.0.6
    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v2.0.0
      with: 
        path: './dist/'
    - name: Deploy GitHub Pages site
      uses: actions/deploy-pages@v2.0.5
